### PR TITLE
Fix keys ids again, Keys - use real id instead of name

### PR DESCRIPTION
**Pull request by johnnyWalnut**
Close #1880 
Keys - use real id instead of name
Refactor key functions in ui and backend. We use key ids to refer to keys
Solve few bugs
Code enhancement
Refactor key api tests
Please run test and merge as soon as possible!

---
This change is [Reviewable](https://reviewable.io/reviews/mistio/mist.io/763)

### CODE REVIEW

**Comment by ptzianos** [comment]
Run tests

**Comment by ptzianos** [comment]
Run tests

**Comment by fakiolinho** [comment]
Run tests

**Comment by dimrozakis** [comment]
@johnnyWalnut, I see that all instances of `Keypair` have been changed to `Key`. The term `key` is too generic. We have API keys, SSH keys, SSL keys, dict keys etc. I'm not saying we should revert it now, but I don't think it was a good choice.

@ptzianos, what's up with the new `tests` submodule? What has been moved there? There are still tests left in this repo, as far as I can tell.

Other than that, the PR seems fine, more or less.

**Comment by ptzianos** [comment]
Because there where still some unmerged branches with additions to tests, I created the tests submodule and started moving the code over there and also change the configuration of Jenkins step by step in order to not break anything. The tests will be completely removed from both mist.io and mist.core next week in a pull request

**Comment by ptzianos** [comment]
Run tests

**Pull request merged**
