### PR TITLE
Add org onboarding

### PR DESCRIPTION
**Pull request by fakiolinho**
@d-mo when you have some time please review this too

---
This change is [Reviewable](https://reviewable.io/reviews/mistio/mist.io/776)

### CODE REVIEW

**Comment by johnnyWalnut** [comment]
@dr please review
The question is merge this, or first migrate users with personal context and then merge

**Comment by dimrozakis** [comment]
@johnnyWalnut this PR has lots of UI changes so I don't think I'm the best person to review this.
/cc @d-mo 

But I see commit messages such as:
>Remove personal context link for users

and you asked:
>The question is merge this, or first migrate users with personal context and then merge

I don't think we can completely deprecate the personal context without:
1) migrating all users to an organizational context
2) fix the billing ui for orgs

**Comment by dimrozakis** [comment]
@johnnyWalnut this PR has lots of UI changes so I don't think I'm the best person to review this.
/cc @d-mo 

Please see the conversation in the corresponding mist.core PR

**Comment by fakiolinho** [comment]
@d-mo when you have some time please review this too

**Comment by d-mo** [comment]
Looks good

**Comment by johnnyWalnut** [comment]
run tests and merge

**Comment by johnnyWalnut** [comment]
not merge
add one more step for sign up
change cretae token in account page for personal/organizational

**Comment by ptzianos** [comment]
Run tests

**Comment by johnnyWalnut** [comment]
add also script that will migrate users without clouds from personal context to organizational context

**Pull request merged**
