### PR TITLE
pass bare metal option - see comments and merge

### PR DESCRIPTION
**Pull request by mgogoulos**
1) merge this first - https://github.com/mistio/libcloud/pull/64
2) make sure cloud_init passed gets it's way to a public https URL and then create_node passes that public https URL as postInstallScriptUri

### CODE REVIEW

**Comment by mgogoulos** [comment]
Run tests

**Comment by mgogoulos** [comment]
Run tetss

**Comment by mgogoulos** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Pull request merged**
