### PR TITLE
Hostvirtual

### PR DESCRIPTION
**Pull request by mgogoulos**
adds support to HostVirtual. First merge https://github.com/mistio/libcloud/pull/33

There are a few issues here that are related to HV API/backend. Their really helpful team are handling them though

1) although the API calls for actions are correct, reboot and start are not working on their backend (shutdown/destroy do work). This might already be fixed by HV however, as they are aware of it

2) list_sizes returns all sizes, but you can't create all sizes to all locations. If you select to deploy a size to a location that does not support it, it will be deployed to another location that supports it. 

HV will make this behavior configurable by the user, so they may allow this, or choose to get notified that the size cannot be deployed to that location

### CODE REVIEW

**Comment by mgogoulos** [comment]
Run tests

**Comment by mgogoulos** [comment]
Run tests

**Comment by commixon** [comment]
Run tests

**Comment by commixon** [comment]
Run tests

**Comment by commixon** [comment]
Run tests

**Pull request merged**
