### PR TITLE
Fix keys

### PR DESCRIPTION
**Pull request by johnnyWalnut**
refactoring keys after mongoengine migration and rbac
change functions and variable names from keypair to key, from key_id to key_name, from keypair_tags to key_tags. So to be consistent...

also use pep8

---
This change is [Reviewable](https://reviewable.io/reviews/mistio/mist.io/748)

### CODE REVIEW

**Comment by d-mo** [comment]
Run tests

**Comment by ptzianos** [comment]
This should not be merged yet because there is still work to be done

**Comment by johnnyWalnut** [comment]
@dimo try again

**Comment by dimrozakis** [comment]
Thousands of lines with pep8 changes along with actual code changes. Sorry, but this isn't reviewable. Split semantically different changes into separate commits.

**Pull request closed without merging**
