### PR TITLE
Polymist

### PR DESCRIPTION
**Pull request by d-mo**
This change is [Reviewable](https://reviewable.io/reviews/mistio/mist.io/815)

### CODE REVIEW

**Comment by xristina** [comment]
Reviewed 7 of 170 files at r1.
Review status: 7 of 170 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/elements/app-costs/app-costs.html, line 199 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLISiAVfLo0M9drFRZr:-KLISiAVfLo0M9drFRZs:62189962) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/app-costs/app-costs.html#L199)):*
> ```HTML
>             return 0;
>         });
>         return topCloudsArray.slice(0,3);
> ```

return topCoudsArray without slicing for Mario's request

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 7 of 170 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/elements/app-fab/app-fab.html, line 78 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIU72ERmfvJ3y4A_Df:-KLIU72ERmfvJ3y4A_Dg:386358231) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/app-fab/app-fab.html#L78)):*
> ```HTML
> 	    }
> 	});
> </script>
> ```

app-fab is not used anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 1 of 170 files at r1.
Review status: 8 of 170 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/elements/app-forms/app-forms.html, line 110 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIUYoPuJbYykuXRH7X:-KLIUYoPuJbYykuXRH7Y:181229840) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/app-forms/app-forms.html#L110)):*
> ```HTML
>     // document.getElementById('form').submit();
> }
> </script>
> ```

not used anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 6 of 170 files at r1.
Review status: 14 of 170 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/elements/app-rules/app-rules.html, line 90 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIVqC-rncck1IWcyUS:-KLIVqC-rncck1IWcyUT:644344523) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/app-rules/app-rules.html#L90)):*
> ```HTML
>     }
> });
> </script>
> ```

not currently used. could of use in machine rules

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 4 of 170 files at r1.
Review status: 18 of 170 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/elements/app-togglable/app-togglable-list.html, line 75 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIXVPZ2RhShwGnEcsi:-KLIXVPZ2RhShwGnEcsj:-93116221) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/app-togglable/app-togglable-list.html#L75)):*
> ```HTML
>     })();
>     </script>
> </dom-module>
> ```

not used, after iterations in stack template and team page. could be of use later

---

*[app/elements/app-togglable/app-togglable.html, line 101 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIY36FsOlLsgsC7Osr:-KLIY36FsOlLsgsC7Oss:-980755151) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/app-togglable/app-togglable.html#L101)):*
> ```HTML
>     })();
>     </script>
> </dom-module>
> ```

not used after iterations in template stack and team page

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 1 of 1 files at r2.
Review status: 19 of 170 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/elements/clouds/cloud-add.html, line 1211 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIYQusaoGLJNM7JnOS:-KLIYQusaoGLJNM7JnOT:1526336036) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/clouds/cloud-add.html#L1211)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

dimo's work will simplify this element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 19 of 170 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/elements/clouds/cloud-chip.html, line 358 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIYi1yA7LfkRyQ4DzZ:-KLIYi1yA7LfkRyQ4Dz_:785807441) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/clouds/cloud-chip.html#L358)):*
> ```HTML
>   </script>
> 
> </dom-module>
> ```

to iterate on: could be simpler and shorter, with only the few things we need. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 4 of 170 files at r1.
Review status: 23 of 170 files reviewed at latest revision, 9 unresolved discussions.

---

*[app/elements/helpers/custom-validator.html, line 14 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIZVAsCMrQnbO4Kcax:-KLIZVAsCMrQnbO4Kcay:596480142) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/helpers/custom-validator.html#L14)):*
> ```HTML
> 
>     });
> </script>
> ```

not used. will be of use

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 9 of 170 files at r1.
Review status: 32 of 170 files reviewed at latest revision, 11 unresolved discussions.

---

*[app/elements/keys/key-edit.html, line 105 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLI_y421wetptjTLWvr:-KLI_y421wetptjTLWvs:-2029940842) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/keys/key-edit.html#L105)):*
> ```HTML
>                     this.$.keyEditAjaxRequest.headers["Csrf-Token"] = CSRF_TOKEN;
>                     this.$.keyEditAjaxRequest.body = {
>                         new_name: this.newKey.name
> ```

this may break. 'new_name' might be needed.

---

*[app/elements/keys/key-edit.html, line 121 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIa6Fuyck3Z80UOcg4:-KLIa6Fuyck3Z80UOcg5:-969990811) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/keys/key-edit.html#L121)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

TODO: show key edit button in key page ang key list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 32 of 170 files reviewed at latest revision, 12 unresolved discussions.

---

*[app/elements/keys/key-page.html, line 554 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIacIMnUzyyOhmYSm8:-KLIacIMnUzyyOhmYSm9:-1902542801) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/keys/key-page.html#L554)):*
> ```HTML
>                     newnot["text"] = msg;
>                     newnot["type"] = 'green';
>                     document.querySelector("notifications-element").notifications.push(newnot);
> ```

4 lines above are tryouts on notifications-element that did not work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 1 of 170 files at r1.
Review status: 33 of 170 files reviewed at latest revision, 13 unresolved discussions.

---

*[app/elements/machines/machine-add.html, line 2114 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIbJBo5IYSfB6EsZu7:-KLIbJBo5IYSfB6EsZu8:1187075756) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/machines/machine-add.html#L2114)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

this has been replaced by machine-create

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 33 of 170 files reviewed at latest revision, 14 unresolved discussions.

---

*[app/elements/machines/machine-create.html, line 2415 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIbZDHnAV4A6lmmZic:-KLIbZDHnAV4A6lmmZid:1142623059) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/machines/machine-create.html#L2415)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

wip. fields should load from other file for better maintenance, maybe provider.js would help

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 33 of 170 files reviewed at latest revision, 15 unresolved discussions.

---

*[app/elements/machines/machine-edit.html, line 42 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIbxDemI4DyTeqG-5d:-KLIbxDemI4DyTeqG-5e:-603536685) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/machines/machine-edit.html#L42)):*
> ```HTML
>         </paper-dialog>
> 
>         <iron-ajax id="editMachineAjax" url="/machines/[[machine.uuid]]" method="POST" on-request="_ajaxRequest" on-response="_ajaxResponse"></iron-ajax>
> ```

this should be api/v1/machines/[[machine.uuid]]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 1 of 170 files at r1.
Review status: 34 of 170 files reviewed at latest revision, 16 unresolved discussions.

---

*[app/elements/machines/machine-tag-item.html, line 34 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIcI5Dfp0ibCmnBcj8:-KLIcI5Dfp0ibCmnBcj9:-588104465) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/machines/machine-tag-item.html#L34)):*
> ```HTML
>         }
>     });
> </script>
> ```

not used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 3 of 170 files at r1.
Review status: 37 of 170 files reviewed at latest revision, 17 unresolved discussions.

---

*[app/elements/members/members-list-element.html, line 294 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIcn-NUAF0tD2Unqfm:-KLIcn-NUAF0tD2Unqfn:2060060659) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/members/members-list-element.html#L294)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

all /members/ elements will be revised

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 37 of 170 files reviewed at latest revision, 18 unresolved discussions.

---

*[app/elements/networks/network-add.html, line 533 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIdib-NL6zVfnOuMFD:-KLIdib0aIMuv_2Xu9gc:797487185) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/networks/network-add.html#L533)):*
> ```HTML
>     })();
>     </script>
> </dom-module>
> ```

requests need testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 2 of 170 files at r1.
Review status: 39 of 170 files reviewed at latest revision, 19 unresolved discussions.

---

*[app/elements/notifications-element/notifications-element.html, line 213 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIeIg6Df56ezAg3dcc:-KLIeIg8VRH2D72UThXW:301479928) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/notifications-element/notifications-element.html#L213)):*
> ```HTML
>     });
>   </script>
> </dom-module>
> ```

wip. to remove from app-header until functional

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Review status: 39 of 170 files reviewed at latest revision, 20 unresolved discussions.

---

*[app/elements/onb-element/onb-element.html, line 117 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIeSZSxl4D9u_cm-Fi:-KLIeSZSxl4D9u_cm-Fj:-2017054048) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/onb-element/onb-element.html#L117)):*
> ```HTML
>         });
>     </script>
> </dom-module>
> ```

not used yet. onb-process  of page-dashboard can be moved in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 14 of 170 files at r1.
Review status: 53 of 170 files reviewed at latest revision, 24 unresolved discussions.

---

*[app/elements/password-page/password-page.html, line 56 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIfkqhTOuhUrk6uLbf:-KLIfkqhTOuhUrk6uLbg:1286346348) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/password-page/password-page.html#L56)):*
> ```HTML
>                         <paper-input label="Current Password" required type="password" error-message="Please enter your old password" value="{{this.currentPassword}}" always-float-label></paper-input>
> 
>                         <paper-input label="New Password" required type="password" error-message="Please enter your new password" value="{{this.newPassword}}" always-float-label></paper-input>
> ```

in inputs we could test and try out `value="{{newPassword::input}}"` syntax.

---

*[app/elements/policies/policy-page-element.html, line 54 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIgXW3zGSQgVcBRHKH:-KLIgXW4B6s7eXhSh0nq:1385199817) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/policies/policy-page-element.html#L54)):*
> ```HTML
>                 },
>                 _computePolicy: function(id) {
>                     return Mist.policies.find(function(policy) {
> ```

this will break. all /policy/ elements to be revisited

---

*[app/elements/scripts/script-edit.html, line 123 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIhJ1xExtFecOI7wcv:-KLIhJ1xExtFecOI7wcw:-1525318381) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/scripts/script-edit.html#L123)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

TODO: show edit button in script page

---

*[app/elements/section-incidents/section-incidents.html, line 15 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIhstX5F6OAVM9623m:-KLIhstYWKRlaVRoY-bz:-1942528071) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/section-incidents/section-incidents.html#L15)):*
> ```HTML
>     enableCustomStyleProperties: true
> });
> </script>
> ```

not used anymore. can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 12 of 170 files at r1.
Review status: 65 of 170 files reviewed at latest revision, 28 unresolved discussions.

---

*[app/elements/stacks/stack-create.html, line 854 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIi_Ciuwj4YoM-rXe5:-KLIi_CjOI_fwYs_xj6A:-998464141) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/stacks/stack-create.html#L854)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

lots of cleanup needed. 

---

*[app/elements/stacks/workflow-form.html, line 249 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIiyTu0Ye8vtXJUFFc:-KLIiyTu0Ye8vtXJUFFd:-2139880635) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/stacks/workflow-form.html#L249)):*
> ```HTML
>         })();
>     </script>
> </dom-module>
> ```

not used anymore after iterations in the stack page. it was meant to deal with workflow request specificities. it has now been replaced by app-form or variation.

---

*[app/elements/tag-link/tag-link.html, line 43 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIjvapVxkPsOlOwBb-:-KLIjvaq4n-uejz7i-6k:513398825) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/tag-link/tag-link.html#L43)):*
> ```HTML
>     }
> });
> </script>
> ```

not used. imported in app-sidebar but unused.

---

*[app/elements/tags/tags-list.html, line 170 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIkFl20zbiRWiUL0d4:-KLIkFl20zbiRWiUL0d5:424142927) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/tags/tags-list.html#L170)):*
> ```HTML
> 
>                     payload = this.newItems.map(function(item) {
>                         var newItem = {};
> ```

this line may cause a bug, where opening tags edit-modal and closing without edit, removes resource's tags.
should maybe write `var newItem = this.tags` to preserve old tags.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 6 of 170 files at r1.
Review status: 71 of 170 files reviewed at latest revision, 29 unresolved discussions.

---

*[app/elements/templates/template-edit.html, line 40 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIlAVm0db6k-fwu7RA:-KLIlAVnyxAW11GgFZuW:-1422053486) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/templates/template-edit.html#L40)):*
> ```HTML
>         </paper-dialog>
> 
>         <iron-ajax id="editScriptAjax" url="/templates/[[template._id]]" method="POST" on-request="_ajaxRequest" on-response="_ajaxResponse"></iron-ajax>
> ```

this should be api/v1/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 3 of 170 files at r1.
Review status: 74 of 170 files reviewed at latest revision, 30 unresolved discussions.

---

*[app/elements/theme-color/theme-color.html, line 65 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIlUKwX0PANlDmDNER:-KLIlUKwX0PANlDmDNES:-74439794) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/theme-color/theme-color.html#L65)):*
> ```HTML
>     }
> });
> </script>
> ```

not used in new design. is imported in app-sidebar but unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 21 of 170 files at r1.
Review status: 95 of 170 files reviewed at latest revision, 31 unresolved discussions.

---

*[app/elements/toast-element/toast-element.html, line 91 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIlkFvOIQUrrqEcXOf:-KLIlkFvOIQUrrqEcXOg:845482759) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/elements/toast-element/toast-element.html#L91)):*
> ```HTML
>     });
>   </script>
> </dom-module>
> ```

not used. paper toast is used instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 63 of 170 files at r1.
Review status: 158 of 170 files reviewed at latest revision, 34 unresolved discussions.

---

*[app/images/hero/random-4.svg, line 25 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIo_eH2Z9o-0R4Ssvv:-KLIo_eH2Z9o-0R4Ssvw:-1368039182) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/images/hero/random-4.svg#L25)):*
> ```SVG
> 		l198.72-45.792L1010.88,1217.664z"/>
> </g>
> </svg>
> ```

all app/images/hero/ could be removed

---

*[app/scripts/common.js, line 1755 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIpaJVnMDbWMid1XoT:-KLIpaJVnMDbWMid1XoU:-1840020603) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/app/scripts/common.js#L1755)):*
> ```JavaScript
>     "Wallis and Futuna", "Western Sahara", "Yemen",
>     "Zambia", "Zimbabwe"
> ];
> ```

providers moved to provider.js
policy_form_fields can remain to be used to policy editing
countries can be used in account page (details and feedback) where they are now redefined

---

*[src/mist/io/tasks.py, line 978 \[r2\]](https://reviewable.io:443/reviews/mistio/mist.io/815#-KLIrzPsxLILmThE2S4Y:-KLIrzPsxLILmThE2S4Z:-971575749) ([raw file](https://github.com/mistio/mist.io/blob/48e9bf7efc98c6eb915a79faf3c6c8379acc8d86/src/mist/io/tasks.py#L978)):*
> ```Python
>         node = {}
>         try:
> ```

is this empty line ok?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by xristina** [comment]
Reviewed 10 of 170 files at r1.
Review status: 168 of 170 files reviewed at latest revision, 34 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Comment by d-mo** [comment]
Reviewed 9 of 170 files at r1, 1 of 1 files at r3.
Review status: 169 of 170 files reviewed at latest revision, 34 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mistio/mist.io/815)*

**Pull request merged**
