### PR TITLE
probe mac addresses & filesystems

### PR DESCRIPTION
**Pull request by d-mo**

### CODE REVIEW

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by mgogoulos** [comment]
I see the df but not the MACs on the template view. Where are they going to be used/shown?

**Comment by d-mo** [comment]
They don't appear in the template (yet). They'll be used initially by a script made for Spirent.

**Pull request merged**
