### PR TITLE
Rename node 

### PR DESCRIPTION
**Pull request by mgogoulos**
FIRST merge https://github.com/mistio/libcloud/pull/29

### CODE REVIEW

**Comment by mgogoulos** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by commixon** [comment]
Run tests

**Pull request merged**
