### PR TITLE
Sorting & infinite scrolling in machines list

### PR DESCRIPTION
**Pull request by d-mo**

### CODE REVIEW

**Comment by ptzianos** [comment]
Need to change the tests for this to work. Will do tomorrow morning,

**Comment by ptzianos** [comment]
Doing it now.

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Comment by d-mo** [comment]
Run tests

**Pull request merged**
