### PR TITLE
Add Vultr support.

### PR DESCRIPTION
**Pull request by KeiroD**
Alright, the Vultr changes have been tested and confirmed to be working on a previous instance of mist.io before I had to make a new mist.io instance with larger specs.

Further testing may be needed but insofar as I can tell, everything looks good here.

### CODE REVIEW

**Comment by mgogoulos** [comment]
Hi and thanks for the PR! I don't have an account in Vultr in order to test this, so I need to know what part of the functionality is covered. Apart from the listing of the VMs, did you try to run actions (start/stop/reboot/destroy)? On the images section, do you get a full listing of the images, as you would see on Vultr's portal? Did you try to create a server? If so, was it deployed with the ssh key you specified?

Thanks and regards,
Markos

**Comment by KeiroD** [comment]
@mgogoulos 

It's fairly easy to obtain an account in Vultr for testing this. In fact, they give you $5 credit JUST to test their stuff out.

Following functions that work for me:

* Image listing — WORKS
* Listing of VMs — WORKS
* Start/Stop/Restart/Destroy/Create — WORKS

SSH keys seem to work fine for me, personally. I will note though that Vultr seems to like inserting more than one SSH keys on a single line, so may not work from within Mist.io if people are unaware of this issue.

A simple fix is to edit the authorized_keys file and ensure the additional keys are on their own lines. I've let them know about this but just wanted you guys to know for sure.

**Comment by mgogoulos** [comment]
Sounds great, will try this out soon and will merge your PR.

**Comment by KeiroD** [comment]
@mgogoulos Vultr confirmed it's a known bug and will be fixed within the next few days re: SSH key issue.

**Comment by KeiroD** [comment]
@mgogoulos How's testing on your end?

**Comment by mgogoulos** [comment]
Hi, I have created an account in vultr but didn't do much so far, will experiment tomorrow though and will write my comments, thanks for the patience

**Comment by mgogoulos** [comment]
Run tests

**Comment by mgogoulos** [comment]
Hi, 

the PR is fine, I have made some changes in order for the ssh keys to work with the creation of nodes in vultr, also to display useful metadata in the list_nodes, and also have added missing functions (as start/stop machine). My commits are on these two branches: 

https://github.com/mistio/mist.io/tree/vultr_mgogoulos
https://github.com/mistio/libcloud/commits/vultr_mgogoulos

I will merge your PR and then apply the above commits, but first you need to sign the contributor agreement. Chris Psaltis will contact you in the following 1-2 days for this. 

Thanks

**Comment by KeiroD** [comment]
@mgogoulos 

Glad to hear the PR is fine! I did a fair amount of testing to make sure it was stable before submitting a PR.

I'll await the contributor agreement e-mail. :)

**Comment by mgogoulos** [comment]
Merging

**Pull request merged**
