### PR TITLE
Tags on single machine, key & script pages

### PR DESCRIPTION
**Pull request by fakiolinho**
1st iteration of tags editing in polymist

Connected with pr in mist.core https://github.com/mistio/mist.core/pull/1988

@d-mo please review when possible!!

---
This change is [Reviewable](https://reviewable.io/reviews/mistio/mist.io/795)

### CODE REVIEW

**Comment by d-mo** [comment]
The listings do not work for me apart from the machine list.

**Comment by johnnyWalnut** [comment]
wait for this, wip also in core!!!

**Comment by johnnyWalnut** [comment]
I am sorry for these pr, we plan to make more iterations but in the end it is too long!
Review and merge
@d-mo  
@dimrozakis

**Comment by fakiolinho** [comment]
DO NOT MERGE

**Pull request merged**
